
  // This file was autogenerated by dynamically running setEnv.ts and using dotenv for managing API key secrecy

  export const environment = {
    production: false,
    firebase: {
      apiKey: 'AIzaSyBGX1hgAExy7dQ6Tv4SVdpLDH-HzbiuqYA',
      authDomain: 'ordinary-traveller.firebaseapp.com',
      projectId: 'ordinary-traveller',
      storageBucket: 'ordinary-traveller.appspot.com',
      messagingSenderId: '864251145',
      appId: '1:864251145:web:57a0226d7a8a63ac5cb7d8',
    },
  };
